Entrega 2/savemesensei/config/routes.rb
Rails.application.routes.draw do
    root 'home#index'
    get 'users' => 'users#index'
    post 'users' => 'users#create'
    get 'users/new' => 'users#new', as: :new_user
    get 'users/:id/edit' => 'users#edit', as: :edit_user
    get 'users/:id' => 'users#show', as: :user
    patch 'users/:id' => 'users#update'
    put 'users/:id' => 'users#update'
    delete 'users/:id' => 'users#destroy'
    get 'notices' => 'notices#index'
    post 'notices' => 'notices#create'
    get 'notices/new' => 'notices#new', as: :new_notice
    get 'notices/:id/edit' => 'notices#edit', as: :edit_notice
    get 'notices/:id' => 'notices#show', as: :notice
    patch 'notices/:id' => 'notices#update'
    put 'notices/:id' => 'notices#update'
    delete 'notices/:id' => 'notices#destroy'

end

Entrega 2/savemesensei/app/models/notice.rb
class Notice < ActiveRecord::Base
    belongs_to :user
    before_save :set_qcomments
    def set_qcomments
        self.qcomments = 0 if self.qcomments.blank?
    end
    validates :title, presence: true
    validates :message, presence: true
    validates :user, presence: true
end

Entrega 2/savemesensei/app/models/user.rb
class User < ActiveRecord::Base
    has_many :notices
    before_save :set_image
    def set_image
        self.image = "pug.jpg" if self.image.blank?
    end
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :location, presence: true
    validates :gender, presence: true
    validates :age, presence: true
    validates :username, presence: true, length: {minimum: 2}
    validates :password, presence: true, length: {minimum: 8}
    validates :email, presence: true, uniqueness: true, format: /\A[a-z0-9\._-]+@[a-z0-9\._-]+\.[a-z]{1,5}\z/
end

Entrega 2/savemesensei/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Entrega 2/savemesensei/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

Entrega 2/savemesensei/app/controllers/notices_controller.rb
class NoticesController < ApplicationController
    def index
        @notices = Notice.all
    end

    def show
        @notice = Notice.find(params[:id])
        @user = @notice.user
        #TODO Agregar avisos
    end

    def new
      @notice = Notice.new
    end

    def edit
        @notice = Notice.find(params[:id])
    end

    def create
        @notice = Notice.new(notice_params)
        if @notice.save
            flash[:notice] = "Aviso creado correctamente"
            redirect_to @notice
        else
          render :new
        end
    end

    def update
        @notice = Notice.find(params[:id])
        if @notice.update(notice_params)
            flash[:notice] = "Aviso editado correctamente"
            redirect_to @notice
        else
            render :edit
        end
    end
    def destroy
        @notice = Notice.find(params[:id])
        @notice.destroy
        flash[:notice] = "Aviso editado correctamente"
        redirect_to notices_url
    end
    private
    def notice_params
        params.require(:notice).permit(:user_id, :title, :message, :qcomments, :created_at)
    end
end

Entrega 2/savemesensei/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        #TODO Agregar avisos
    end

    def new
      @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Usuario creado correctamente"
            redirect_to @user
        else
          render :new
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Usuario editado correctamente"
            redirect_to @user
        else
            render :edit
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:notice] = "Usuario editado correctamente"
        redirect_to users_url
    end
    private
    def user_params
        params.require(:user).permit(:username, :password, :email, :first_name, :last_name, :age, :gender, :location)
    end
end

Entrega 2/savemesensei/app/helpers/application_helper.rb
module ApplicationHelper
end

Entrega 2/savemesensei/app/helpers/home_helper.rb
module HomeHelper
end

Entrega 2/savemesensei/app/helpers/notices_helper.rb
module NoticesHelper
end

Entrega 2/savemesensei/app/helpers/users_helper.rb
module UsersHelper
end

Entrega 2/savemesensei/app/views/home/index.html.erb
<h1>¡Bienvenido a Save me Sensei!</h1>
<p>
    Estamos en construcción...
</p>
<p>
    Por mientras puedes ver los CRUD de los usuarios y lo avisos que usaremos.
</p>
<%= link_to "Usuarios", users_path %>
<%= link_to 'Avisos', notices_path %>

Entrega 2/savemesensei/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Savemesensei</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Entrega 2/savemesensei/app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
    <% if @notice.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %>, no se pudo guardar el aviso</h2>
            <ul>
                <% @notice.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :message %><br>
        <%= f.text_field :message %>
    </div>
    <div class="field">
        <%= f.label :qcomments %><br>
        <%= f.number_field :qcomments %>
    </div>
    <div class="field">
        <%= f.label :created_at %><br>
        <%= f.text_field :created_at %>
    </div>
    <div class="field">
        <%= f.label :user %><br>
        <%= f.collection_select :user_id, User.order(:username),:id,:username, include_blank: true %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

Entrega 2/savemesensei/app/views/notices/edit.html.erb
<%= render 'form' %>

<%= link_to 'Ver aviso', notice_path(@notice) %>
<%= link_to 'Volver', notices_path %>

Entrega 2/savemesensei/app/views/notices/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="notices-index">
    <% @notices.each do |n| %>
    <div class="notice-index">
        <div class="title-notice-index">
            <%= n.title %>
        </div>
        <div class="message-notice-index">
            <%= n.message %>
        </div>
        <%= link_to 'Más', n %>
        <%= link_to 'Editar', edit_notice_path(n) %>
        <%= link_to 'Eliminar', n, method: :delete, data: { confirm: '¿Estás seguro?'} %>
    </div>
    <% end %>
    <%= link_to 'Nuevo aviso', new_notice_path %>
    <%= link_to 'Home', '/' %>
</div>

Entrega 2/savemesensei/app/views/notices/new.html.erb
<%= render 'form' %>
<%= link_to 'Volver', notices_path %>

Entrega 2/savemesensei/app/views/notices/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="notices-show">
    <div class="title-notices-show">
        <h1><%= @notice.title %></h1>
    </div>
    <div class="user-notices-show">
        <p>
            Escrito por <%= @user.first_name + ' ' + @user.last_name %>
        </p>
    </div>
    <div class="message-notices-show">
        <%= @notice.message %>
    </div>
    <div class="created-notices-show">
        <p>
            Escrito a las <%= @notice.created_at %>
        </p>
    </div>
    <div class="created-notices-show">
        <p>
            Cantidad de comentarios: <%= @notice.qcomments %>
        </p>
    </div>
    <%= link_to 'Editar', edit_notice_path(@notice) %>
    <%= link_to 'Eliminar', @notice, method: :delete, data: { confirm: '¿Estás seguro?'} %>
    <%= link_to 'Volver', notices_path %>
</div>

Entrega 2/savemesensei/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %>, no se pudo guardar el usuario.</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.label :username %><br>
        <%= f.text_field :username %>
    </div>
    <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :email %><br>
        <%= f.email_field :email %>
    </div>
    <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
    </div>
    <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
    </div>
    <div class="field">
        <%= f.label :location %><br>
        <%= f.text_field :location %>
    </div>
    <div class="field">
        <%= f.label :age %><br>
        <%= f.number_field :age %>
    </div>
    <div class="field">
        <%= f.label :gender %><br>
        <%= f.select(:gender) do %>
            <% [['Hombre', 'Hombre'], ['Mujer', 'Mujer']].each do |c| -%>
                <%= content_tag(:option, c.first, value: c.last) %>
            <% end %>
        <% end %>
    </div>
    <div class="field">
        <%= f.label :image %><br>
        <%= f.text_field :image %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

Entrega 2/savemesensei/app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Ver usuario', user_path(@user) %>
<%= link_to 'Volver', users_path %>

Entrega 2/savemesensei/app/views/users/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="users-index">
    <% @users.each do |u| %>
    <div class="user-index">
        <div class="avatar-user-index">
            <%= image_tag u.image %>
        </div>
        <div class="name-user-index">
            <%= u.first_name + ' ' + u.last_name %>
        </div>
        <%= link_to 'Más', u %>
        <%= link_to 'Editar', edit_user_path(u) %>
        <%= link_to 'Eliminar', u, method: :delete, data: { confirm: '¿Estás seguro?'} %>
    </div>
    <% end %>
    <%= link_to 'Nuevo usuario', new_user_path %>
    <%= link_to 'Home', '/' %>
</div>

Entrega 2/savemesensei/app/views/users/new.html.erb
<%= render 'form' %>
<%= link_to 'Volver', users_path %>

Entrega 2/savemesensei/app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="users-show">
    <div class="image-users-show">
        <%= image_tag @user.image %>
    </div>
    <div class="name-users-show">
        <%= @user.first_name + ' ' + @user.last_name %>
    </div>
    <div class="info-users-show">
        <p>Username: <%= @user.username %></p>
        <p>Email: <%= @user.email %></p>
        <p>Edad: <%= @user.age %></p>
        <p>Género: <%= @user.gender %></p>
        <p>Localización: <%= @user.location %></p>
    </div>
    <%= link_to 'Editar', edit_user_path(@user) %>
    <%= link_to 'Eliminar', @user, method: :delete, data: { confirm: '¿Estás seguro?'} %>
    <%= link_to 'Volver', users_path %>
</div>